name: .NET MAUI Build and Test

on: push

jobs:      
  build-and-test:
    runs-on: windows-latest
       
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET    
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x    
        
    - name: Install MAUI
      run: dotnet workload install maui
      
    - name: Restore NuGet packages
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release 
        
    - name: Test
      run: dotnet test -c Release --no-build
